language: python
python:
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - py.test --durations=10 --cov pyconza2014 --cov-report term-missing tests
    - flake8 setup.py pyconza2014 tests
after_success:
  - coveralls
